<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Nominatif extends Model
{
    protected $table = 'tbl_nominatif'; // Nama tabel

    protected $fillable = [
                    'KD_CAB_KONSOL',
                    'KD_CAB',
                    'NO_REK',
                    'NO_NASABAH',
                    'NAMA_SINGKAT',
                    'TGL_JT',
                    'JNK_WKT_BL',
                    'PRS_BUNGA',
                    'PLAFOND',
                    'PLAFOND_AWAL',
                    'LONGGAR_TARIK',
                    'KD_STATUS',
                    'BUNGA',
                    'POKOK',
                    'KOLEKTIBILITY',
                    'KD_PRD',
                    'GL_PRD_NAME',
                    'PRD_NAME',
                    'SALDO_AKHIR',
                    'SALDO_AKHIR_NERACA',
                    'AMORSISA',
                    'KODE_APL',
                    'AMOR_BLN_INI',
                    'TOTAGUNAN',
                    'TOTAGUNAN_YDP',
                    'IMPAIREMENT',
                    'CKPN',
                    'TGLMULAI',
                    'AKMAMOR',
                    'JENIS_KREDIT',
                    'SEKTOR_EKONOMI',
                    'GOLONGAN',
                    'HUB_BANK',
                    'ACRU_BLN',
                    'TUNGG_POKOK',
                    'TUNGG_BUNGA',
                    'TREASURID',
                    'CRNBR',
                    'AMTPENPASD',
                    'JENIS_GUNA',
                    'GOL_NSB_LBU',
                    'GOL_NSB_SID',
                    'GOL_KRD_SID',
                    'CATPORTOLBU',
                    'TGL_PK',
                    'NO_PK',
                    'KD_AO',
                    'ANGS_POKOK',
                    'ANGS_BUNGA',
                    'DENDA_TUNGGBNG',
                    'DENDA_TUNGGPKK',
                    'JNSBUNGA',
                    'RATING',
                    'RECOVERY_RATE',
                    'NILAI_AGUNAN',
                    'GROUPID',
                    'QUALITYID',
                    'JML_HARI_TUNGPKK',
                    'JML_HARI_TUNGBNG',
                    'NOHP',
                    'NILAI_WAJAR',
                    'NIK',
                    'NPWP',
                    'NEW_AGUNAN_YDP',
                    'NEW_NILAI_AGUNAN',
                    'STSIMPR',
                    'TGL_AWAL_RSTRK',
                    'TGL_AKHIR_RSTRK',
                    'RESTRUKKE',
                    'QUALRPTO',
                    'RESTRUKTYPE',
                    'PARMNM',
                    'TGL_PENCAIRAN',
                    'SUMBER_DANA',
                    'KT_DEBITUR',
                    'INKLUSIF_MACROPRUDENSIAL',
                    'PEMBIAYAAN_BERKELANJUTAN',
                    'SEGMENT_KREDIT',
                    'SEK_EKO_LBUT',
                    'SEK_EKO_THI',
                    'AUTO_HIJAU_THI',
                    'KLASIFIKASI_THI',
                    'SKOR_KREDIT',
                    'RISK_GRADE',
                    'TANGGAL',
    ];

    public $timestamps = false; // Jika tabel tidak memiliki kolom created_at dan updated_at
}
